<?php
/* USE THE FOLLOWING 7 LINES AS A TEMPLATE
          "_XXXX" => array(
  "ru" => "",
  "en" => "",
  "de" => "",
  "es" => "",
  "fr" => "",
  "pt" => "",
  "it" => ""),
*/
  $gstring = array(
          "_MINI" => array(
  "ru" => "минимум: ",
  "en" => "Minimum: ",
  "de" => "Minimum: ",
  "es" => "Mínimo: ",
  "fr" => "Minimum: ",
  "pt" => "Mínimo: ",
  "it" => "Minimo: "),
          "_MAXI" => array(
  "ru" => "максимум: ",
  "en" => "Maximum: ",
  "de" => "Maximum: ",
  "es" => "Máximo: ",
  "fr" => "Maximum: ",
  "pt" => "Máximo: ",
  "it" => "Massimo: "),
          "_AVER" => array(
  "ru" => "среднее число: ",
  "en" => "Average: ",
  "de" => "Durchschnitt: ",
  "es" => "Promedio: ",
  "fr" => "Minimum: ",
  "pt" => "Média: ",
  "it" => "Media: "),
          "_DTIM" => array(
  "ru" => "<span class='ngrun'>Тест Дата и время:: </span>",
  "en" => "<span class='ngrun'>Test Date-Time: </span>",
  "de" => "<span class='ngrun'>Test-Datum-Zeit: </span>",
  "es" => "<span class='ngrun'>Prueba Fecha-Hora: </span>",
  "fr" => "<span class='ngrun'>Test Date-Heure: </span>",
  "pt" => "<span class='ngrun'>Data do teste-Hora: </span>",
  "it" => "<span class='ngrun'>Prova Data-Ora: </span>"),
          "_DONE" => array(
  "ru" => "<div id='prfid'>Результаты экзамена</div><span id='offff' class='fa fa-times'></span>",
  "en" => "<div id='prfid'>Exam Results</div><span id='offff' class='fa fa-times'></span>",
  "de" => "<div id='prfid'>Prüfungsergebnisse</div><span id='offff' class='fa fa-times'></span>",
  "es" => "<div id='prfid'>Resultados de examen</div><span id='offff' class='fa fa-times'></span>",
  "fr" => "<div id='prfid'>Résultats d'examen</div><span id='offff' class='fa fa-times'></span>",
  "pt" => "<div id='prfid'>Resultados dos exames</div><span id='offff' class='fa fa-times'></span>",
  "it" => "<div id='prfid'>Risultati degli esami</div><span id='offff' class='fa fa-times'></span>"),
          "_SCOR" => array(
  "ru" => "отметка : ",
  "en" => "Score : ",
  "de" => "Punktzahl : ",
  "es" => "Puntaje : ",
  "fr" => "Score : ",
  "pt" => "Pontuação : ",
  "it" => "Punteggio : "),
          "_XART" => array(
  "ru" => "<span class='ngrun'>Тип сессии : </span>",
  "en" => "<span class='ngrun'>Type of Session : </span>",
  "de" => "<span class='ngrun'>Art der Sitzung : </span>",
  "es" => "<span class='ngrun'>Tipo de Sesión : </span>",
  "fr" => "<span class='ngrun'>Genre de Séance : </span>",
  "pt" => "<span class='ngrun'>Tipo de sessão : </span>",
  "it" => "<span class='ngrun'>Tipo di sessione : </span>"),
          "_LOBE" => array(
  "ru" => "Ваша производительность улучшилась<br/>",
  "en" => "Your performance has improved<br/>",
  "de" => "Ihre Leistung hat sich verbessert<br/>",
  "es" => "Su desempeño ha mejorado<br/>",
  "fr" => "Votre performance est améliorée<br/>",
  "pt" => "Seu desempenho melhorou<br/>",
  "it" => "La vostra performance è migliorata<br/>"),
          "_TADL" => array(
  "ru" => "Ваше выступление ухудшилось<br/>",
  "en" => "Your performance has deteriorated<br/>",
  "de" => "Ihre Leistung hat sich verschlechtert<br/>",
  "es" => "Su rendimiento se ha deteriorado<br/>",
  "fr" => "Votre performance se est détériorée<br/>",
  "pt" => "Seu desempenho se deteriorou<br/>",
  "it" => "La vostra performance è deteriorata<br/>"),
          "_ALFA" => array(
  "ru" => "Отлично сработано! Вы владеете верхней отметки",
  "en" => "Well done! You own the Top Score",
  "de" => "Gut gemacht! Sie besitzen die höchste Punktzahl",
  "es" => "Muy bien! El puntaje más alto ahora es el suyo",
  "fr" => "Bravo! Vous possédez le Meilleur Score",
  "pt" => "Bem feito! Você já possui a Pontuação Máxima",
  "it" => "Ben fatto! Già il punteggio più alto"),
          "_ETAL" => array(
  "ru" => "<span class='nnero'> ... и другие ... </span>",
  "en" => "<span class='nnero'> ... and others ... </span>",
  "de" => "<span class='nnero'> ... und andere ... </span>",
  "es" => "<span class='nnero'> ... entre otras ... </span>",
  "fr" => "<span class='nnero'> ... et d&#39;autres ... </span>",
  "pt" => "<span class='nnero'> ... e outras ... </span>",
  "it" => "<span class='nnero'> ... e altre ... </span>"),
          "_ACHT" => array(
  "ru" => "<br/><span class='nnero'>Обратите внимание на эти вопросы</span><br/>",
  "en" => "<br/><span class='nnero'>Pay attention to these questions</span><br/>",
  "de" => "<br/><span class='nnero'>Achten Sie auf diese Fragen</span><br/>",
  "es" => "<br/><span class='nnero'>Preste atención a estas preguntas</span><br/>",
  "fr" => "<br/><span class='nnero'>Faites attention à ces questions</span><br/>",
  "pt" => "<br/><span class='nnero'>Preste atenção a estas questões</span><br/>",
  "it" => "<br/><span class='nnero'>Prestare attenzione a queste domande</span><br/>"),
          "_SHAM" => array(
  "ru" => "Доля по электронной почте",
  "en" => "Share per email",
  "de" => "Teilen Sie per E-Mail",
  "es" => "Compartir por correo electrónico",
  "fr" => "Partager par email",
  "pt" => "Compartilhar por e-mail",
  "it" => "Condividi via email"),
          "_LERN" => array(
  "ru" => "★★ сегодня я узнал кое-что ★★",
  "en" => "★★ I learned something today ★★",
  "de" => "★★ Heute habe Ich habe etwas gelernt ★★",
  "es" => "★★ He aprendido algo hoy ★★",
  "fr" => "★★ J'ai appris quelque chose aujourd'hui ★★",
  "pt" => "★★ Eu aprendi alguma coisa hoje ★★",
  "it" => "★★ Oggi ho imparato qualcosa ★★"),
          "_BEFO" => array(
  "ru" => "<div class='ngrun'>Предварительные результаты испытаний : </div>",
  "en" => "<div class='ngrun'>Prior test results : </div>",
  "de" => "<div class='ngrun'>Vorherige Testergebnisse : </div>",
  "es" => "<div class='ngrun'>Resultados de las pruebas anteriores : </div>",
  "fr" => "<div class='ngrun'>Les résultats des tests antérieurs : </div>",
  "pt" => "<div class='ngrun'>Os resultados dos testes anteriores : </div>",
  "it" => "<div class='ngrun'>Risultati dei test precedenti : </div>"),
          "_SENT" => array(
  "ru" => "<span class='nnero'>Электронное сообщение с этим докладом был отправлен : </span>",
  "en" => "<span class='nnero'>An email with this report has been sent to : </span>",
  "de" => "<span class='nnero'>Eine E-Mail mit diesem Bericht wurde versendet an : </span>",
  "es" => "<span class='nnero'>Un correo electrónico con este informe ha sido enviado a : </span>",
  "fr" => "<span class='nnero'>Un email avec ce rapport a été envoyé à : </span>",
  "pt" => "<span class='nnero'>Um e-mail com este relatório foi enviado para : </span>",
  "it" => "<span class='nnero'>Una e-mail con la presente relazione è stata inviata a : </span>"),
          "_FOWD" => array(
  "ru" => "<span class='nnero'>Здесь вы можете поделиться этими результатами ⇒  </span>",
  "en" => "<span class='nnero'>Here you can share these results ⇒  </span>",
  "de" => "<span class='nnero'>Hier können Sie diese Ergebnisse teilen ⇒  </span>",
  "es" => "<span class='nnero'>Aquí puede compartir estos resultados ⇒  </span>",
  "fr" => "<span class='nnero'>Ici vous pouvez partager ces résultats ⇒  </span>",
  "pt" => "<span class='nnero'>Aqui você pode compartilhar esses resultados ⇒  </span>",
  "it" => "<span class='nnero'>Qui è possibile condividere questi risultati ⇒  </span>"),
          "_GOOD" => array(
  "ru" => "<br/><span class='nnero' style='float:left;clear:left;'>Считаете ли вы эту испытание полезно ?</span>&nbsp;&nbsp;",
  "en" => "<br/><span class='nnero' style='float:left;clear:left;'>Did you find this Test useful ?</span>&nbsp;&nbsp;",
  "de" => "<br/><span class='nnero' style='float:left;clear:left;'>Hat dieser Test Ihnen geholfen ?</span>&nbsp;&nbsp;",
  "es" => "<br/><span class='nnero' style='float:left;clear:left;'>¿ Le ha resultado útil esta prueba ?</span>&nbsp;&nbsp;",
  "fr" => "<br/><span class='nnero' style='float:left;clear:left;'>Avez-vous trouvé ce test utile ?</span>&nbsp;&nbsp;",
  "pt" => "<br/><span class='nnero' style='float:left;clear:left;'>Considera que este teste é útil ?</span>&nbsp;&nbsp;",
  "it" => "<br/><span class='nnero' style='float:left;clear:left;'>Hai trovato che questa prova è utile ?</span>&nbsp;&nbsp;"),
          "_FEED" => array(
  "ru" => "<br/><span class='nnero'>Тебе есть что добавить ?</span>",
  "en" => "<br/><span class='nnero'>Do you have any comments ?</span>",
  "de" => "<br/><span class='nnero'>Möchten Sie einen Kommentar hinzufügen ?</span>",
  "es" => "<br/><span class='nnero'>¿ Tiene algún comentario ?</span>",
  "fr" => "<br/><span class='nnero'>Avez-vous des commentaires ?</span>",
  "pt" => "<br/><span class='nnero'>Você tem algum comentário ?</span>",
  "it" => "<br/><span class='nnero'>Hai un commento ?</span>"),
          "_RECO" => array(
  "ru" => "<br/><span class='nnero'>Вы рекомендовали бы этот тест ?</span>",
  "en" => "<br/><span class='nnero'>Would you recommend this test ?</span>",
  "de" => "<br/><span class='nnero'>Möchten Sie diesen Test empfehlen ?</span>",
  "es" => "<br/><span class='nnero'>¿ Usted Recomendaría esta prueba ?</span>",
  "fr" => "<br/><span class='nnero'>Recommanderiez-vous ce test ?</span>",
  "pt" => "<br/><span class='nnero'>Você recomendaria este teste ?</span>",
  "it" => "<br/><span class='nnero'>Consiglieresti questo test ?</span>")
  );
function pglot($s2xlate){
   global $gstring;
   foreach($s2xlate as $str) $retAR[] = $gstring["$str"][$_SESSION['slang']];
   return($retAR);
}
?>
